[package]
name = "calculate-the-area-of-a-regular-n-sides-polygon-inside-a-circle-of-radius-r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
