[package]
name = "take-a-number-and-sum-its-digits-raised-to-the-consecutive-powers-and-eureka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
